env:
app:
  application: 'NLE'
  hostname: 'local'
  server:
    host: 'http://localhost:3000'
    port: 3000
  nuls:
    host: http://localhost:6001
    base: '/api'
    resources: 
      getLastHeight: /block/newest/height
      getBlock: /block/header/height/__BLOCK_HEIGHT__
      getBlockBytes: /block/bytes?hash=__BLOCK_HASH__
      contractInfo: /contract/info/__ADDRESS__
      contractView: /contract/view
      contractCallValidate: /contract/validate/call
      contractCallGas: /contract/imputedgas/call
      broadcastTx: /accountledger/transaction/broadcast
  level:
    path: /data/nuls-light-explorer
    databases:
      common: 
        name: common
        port: 3090
      hashHeight:
        name: hashHeight
        port: 3091
      heightBlock: 
        name: heightBlock
        port: 3092
      hashTransaction: 
        name: hashTransaction
        port: 3093
      addressUtxos:
        name: addressUtxos
        port: 3094
      heightBlockBytes: 
        name: heightBlockBytes
        port: 3095
  jobs:
    retryTimeout: 8
    blockTime: 10
  logger:
    logLevel: debug